# Generated by Django 3.2.9 on 2021-11-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pintrest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters'),
        ),
    ]
