# Generated by Django 3.2.9 on 2021-11-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pintrest', '0002_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('budget', models.IntegerField(blank=True, default=0, null=True)),
                ('poster', models.ImageField(null=True, upload_to='posters')),
                ('cast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movies', to='pintrest.cast')),
                ('category', models.ManyToManyField(blank=True, related_name='media', to='pintrest.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Seires',
            fields=[
                ('production_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pintrest.production')),
                ('num_of_episodes', models.IntegerField(blank=True, null=True)),
            ],
            bases=('pintrest.production',),
        ),
    ]
